/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("xyz.jpenilla.run-paper") version "2.1.0"
    java
    `maven-publish`
    idea
}

repositories {
    mavenCentral()
    mavenLocal()

    maven {
        name = "papermc"
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.essentialsx.net/releases/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        name = "nickapi"
        url = uri("https://haoshoku.xyz:8081/repository/default/")
    }
}

dependencies {
    compileOnly("me.clip:placeholderapi:2.11.6")
    compileOnly("org.spigotmc:spigot-api:1.20.1-R0.1-SNAPSHOT")
    compileOnly("net.ess3:EssentialsX:2.18.2")
    compileOnly("com.github.Brikster:Chatty:v2.19.4") {
        exclude("org.bstats")

    }
    compileOnly("xyz.haoshoku.nick:nickapi:7.5")

    // https://mvnrepository.com/artifact/org.jetbrains/annotations
    implementation("org.jetbrains:annotations:24.0.1")

    // https://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple
    implementation("com.googlecode.json-simple:json-simple:1.1.1")

    implementation("io.papermc:paperlib:1.0.7")
}

group = "groupId"
version = "2.8_PRE_2"
description = "ChatPings"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks {
    runServer {
        // Configure the Minecraft version for our task.
        // This is the only required configuration besides applying the plugin.
        // Your plugin's jar (or shadowJar if present) will be used automatically.
        minecraftVersion("1.21.1")
    }
}
